data:
  env_name: "ALE/PongNoFrameskip-v4"
  # "ALE/BreakoutNoFrameskip-v4"
  # "ALE/SpaceInvadersNoFrameskip-v4"
  
  total_transitions: 100000
  num_episodes: 200
  
logging:
  save_dir: "data"  # Relative path

buffer:
  max_size: 100000
  state_shape: [4, 84, 84]
